name: boostly-backend

services:
  backend:
    image: boostly-backend
    container_name: boostly-backend-container
    build: .
    command: /app/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boostlyDB

  ngrok:
    image: ngrok/ngrok
    container_name: ngrok-container
    env_file:
      - .env
    command: http backend:8000
    depends_on:
      - backend

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  celery:
    image: boostly-backend
    container_name: celery
    command: celery -A backend worker --loglevel=info
    depends_on:
      - redis
      - postgres
      - backend
