# Generated by Django 4.2.5 on 2024-10-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
